"""empty message

Revision ID: ab9422ed04c7
Revises: dae1a28969aa
Create Date: 2022-09-19 20:39:25.700927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9422ed04c7'
down_revision = 'dae1a28969aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupo_de_apoio', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('grupo_de_apoio_user__id_fkey', 'grupo_de_apoio', type_='foreignkey')
    op.create_foreign_key(None, 'grupo_de_apoio', 'user', ['user_id'], ['id'])
    op.drop_column('grupo_de_apoio', 'user__id')
    op.add_column('post', sa.Column('grupo_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('txt', sa.String(length=300), nullable=False))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_user__id_fkey', 'post', type_='foreignkey')
    op.drop_constraint('post_grupo__id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'grupo_de_apoio', ['grupo_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'user__id')
    op.drop_column('post', 'grupo__id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('grupo__id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('user__id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_grupo__id_fkey', 'post', 'grupo_de_apoio', ['grupo__id'], ['id'])
    op.create_foreign_key('post_user__id_fkey', 'post', 'user', ['user__id'], ['id'])
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'txt')
    op.drop_column('post', 'grupo_id')
    op.add_column('grupo_de_apoio', sa.Column('user__id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grupo_de_apoio', type_='foreignkey')
    op.create_foreign_key('grupo_de_apoio_user__id_fkey', 'grupo_de_apoio', 'user', ['user__id'], ['id'])
    op.drop_column('grupo_de_apoio', 'user_id')
    # ### end Alembic commands ###
