"""empty message

Revision ID: dae1a28969aa
Revises: f07621495e40
Create Date: 2022-09-19 17:32:51.494140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae1a28969aa'
down_revision = 'f07621495e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_post', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
