"""empty message

Revision ID: f07621495e40
Revises: 7b341695f43f
Create Date: 2022-09-19 17:19:55.364791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07621495e40'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol')
    )
    op.create_table('grupo_de_apoio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('tema', sa.String(length=250), nullable=False),
    sa.Column('user__id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user__id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesional_de_la_salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grado', sa.String(length=250), nullable=False),
    sa.Column('especialidad', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user__id', sa.Integer(), nullable=True),
    sa.Column('grupo__id', sa.Integer(), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grupo__id'], ['grupo_de_apoio.id'], ),
    sa.ForeignKeyConstraint(['user__id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('id_post', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'rol_id')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'id_post')
    op.drop_table('post')
    op.drop_table('profesional_de_la_salud')
    op.drop_table('grupo_de_apoio')
    op.drop_table('rol')
    # ### end Alembic commands ###
